#!/bin/sh
# Sourced by verification and publication so both use the same tags.
: "${CI_REGISTRY_IMAGE:?Set CI_REGISTRY_IMAGE}"
: "${CI_COMMIT_REF_SLUG:?Set CI_COMMIT_REF_SLUG}"
: "${CI_COMMIT_SHORT_SHA:?Set CI_COMMIT_SHORT_SHA}"
: "${CI_COMMIT_SHA:?Set CI_COMMIT_SHA}"
export IMAGE_TAG="$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
export ADDITIONAL_IMAGE_TAG="$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
export REVISION="$CI_COMMIT_SHA"
